services:
  aptly:
    build: .
    command: tail -f /dev/null
    environment:
      - GIN_MODE=release
    volumes:
      - '{{ vault_repo_workdir }}/aptly/volume/:{{ vault_repo_workdir }}:z'
      - '{{ vault_repo_workdir }}/aptly/docker/aptly.conf:/etc/aptly.conf'
      - '{{ vault_repo_workdir }}/aptly/docker/.gnupg/:/root/.gnupg/'
    deploy:
      restart_policy:
        condition: any

  bandersnatch:
    image: pypa/bandersnatch
    volumes:
      - '{{ vault_repo_workdir }}/bandersnatch/docker/bandersnatch.conf:/conf/bandersnatch.conf:ro'
      - '{{ vault_repo_workdir }}/bandersnatch/pypi/:/srv/pypi/'
    deploy:
      restart_policy:
        condition: any

  nginx:
    image: nginx
    volumes:
      - '{{ vault_repo_workdir }}/aptly/volume/public/:{{ vault_repo_workdir }}/aptly/:ro,z'
      - '{{ vault_repo_workdir }}/bandersnatch/pypi/web/:{{ vault_repo_workdir }}/bandersnatch/:ro,z'
      - '{{ vault_repo_workdir }}/nginx/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    deploy:
      restart_policy:
        condition: any
