version: '2'
   
services:
  aptly:
    build: .
    command: tail -f /dev/null
    environment:
      - GIN_MODE=release
    volumes:
      - '{{ aptly_workdir }}/volume/:{{ aptly_workdir }}:z'
      - '{{ aptly_workdir }}/docker/aptly.conf:/etc/aptly.conf'
      - '{{ aptly_workdir }}/docker/.gnupg/:/root/.gnupg/'

  nginx:
    image: nginx
    volumes:
      - '{{ aptly_workdir }}/volume/public/:{{ aptly_workdir }}:ro,z'
      - '{{ aptly_workdir }}/docker/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
