- name: 'Add repository public key'
  ansible.builtin.apt_key:
    url: 'http://{{ repo_fqdn }}/repo.key'
    state: present

- name: 'Add repository'
  ansible.builtin.apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
    - 'deb http://{{ repo_fqdn }}/deb/ubuntu {{ ansible_distribution_release }} main restricted'
    - 'deb http://{{ repo_fqdn }}/deb/ubuntu {{ ansible_distribution_release }}-updates main restricted'
    - 'deb http://{{ repo_fqdn }}/deb/ubuntu {{ ansible_distribution_release }} universe'
    - 'deb http://{{ repo_fqdn }}/deb/ubuntu {{ ansible_distribution_release }}-updates universe'
    - 'deb http://{{ repo_fqdn }}/deb/ubuntu {{ ansible_distribution_release }} multiverse'
    - 'deb http://{{ repo_fqdn }}/deb/ubuntu {{ ansible_distribution_release }}-updates multiverse'
    - 'deb http://{{ repo_fqdn }}/deb/ubuntu {{ ansible_distribution_release }}-backports main restricted universe multiverse'
    - 'deb http://{{ repo_fqdn }}/deb/ubuntu {{ ansible_distribution_release }}-security main restricted'
    - 'deb http://{{ repo_fqdn }}/deb/ubuntu {{ ansible_distribution_release }}-security universe'
    - 'deb http://{{ repo_fqdn }}/deb/ubuntu {{ ansible_distribution_release }}-security multiverse'

- name: 'Update repositories cache'
  ansible.builtin.apt:
    update_cache: yes
